# Generated by Django 2.0.7 on 2019-11-14 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalancedPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GAmount', models.IntegerField()),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emp_reward.employee')),
            ],
        ),
        migrations.CreateModel(
            name='GiftTrans',
            fields=[
                ('GTransId', models.IntegerField(primary_key=True, serialize=False)),
                ('GTransDate', models.DateField()),
                ('giftcardAmount', models.IntegerField()),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emp_reward.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PointTrans',
            fields=[
                ('PTransId', models.IntegerField(primary_key=True, serialize=False)),
                ('PTransDate', models.DateField()),
                ('pointAmount', models.IntegerField()),
                ('received_eId', models.IntegerField()),
                ('given_eId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emp_reward.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RecievedPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAmount', models.IntegerField()),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emp_reward.employee')),
            ],
        ),
        migrations.AddField(
            model_name='balancedpoints',
            name='eid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emp_reward.employee'),
        ),
    ]
