# Generated by Django 2.0.7 on 2019-11-16 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCards',
            fields=[
                ('GTransId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('GAmount', models.IntegerField(null=True)),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('PAmountReceived', models.IntegerField()),
                ('balanceLeft', models.IntegerField()),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointTrans',
            fields=[
                ('PTransId', models.AutoField(primary_key=True, serialize=False)),
                ('PTransDate', models.DateTimeField(null=True)),
                ('pointAmount', models.IntegerField()),
                ('message', models.CharField(max_length=240, null=True)),
                ('given_eId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_given_by', to=settings.AUTH_USER_MODEL)),
                ('received_eId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_received_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAmount', models.IntegerField()),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
