# Generated by Django 2.0.7 on 2019-11-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtrans',
            name='PTransDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
