# Generated by Django 2.0.7 on 2019-11-14 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_reward', '0002_auto_20191114_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievedpoints',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 22, 47, 22, 874112)),
        ),
    ]
