# Generated by Django 2.0.7 on 2019-11-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_reward', '0003_auto_20191116_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcards',
            name='eid',
        ),
        migrations.DeleteModel(
            name='GiftCards',
        ),
    ]
