# Generated by Django 2.0.7 on 2019-11-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp_reward', '0004_auto_20191116_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCards',
            fields=[
                ('GTransId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('GAmount', models.IntegerField(null=True)),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
