# Generated by Django 2.0.7 on 2019-11-15 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_reward', '0011_totalpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtrans',
            name='message',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='pointtrans',
            name='PTransId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pointtrans',
            name='given_eId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_given_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointtrans',
            name='received_eId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_received_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
