# Generated by Django 2.0.7 on 2019-11-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_reward', '0014_auto_20191115_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtrans',
            name='PTransDate',
            field=models.DateTimeField(null=True),
        ),
    ]
