# Generated by Django 2.0.7 on 2019-11-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_reward', '0015_auto_20191115_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifttrans',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='giftcards',
            name='id',
        ),
        migrations.AddField(
            model_name='giftcards',
            name='GTransId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcards',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='giftcards',
            name='GAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='GiftTrans',
        ),
    ]
