# Generated by Django 2.0.7 on 2019-11-14 22:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recievedpoints',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 22, 45, 50, 424814)),
        ),
        migrations.AlterField(
            model_name='balancedpoints',
            name='eid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftcards',
            name='eid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gifttrans',
            name='eid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointtrans',
            name='given_eId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recievedpoints',
            name='eid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
