# Generated by Django 2.0.7 on 2019-11-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_reward', '0009_auto_20191115_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalpoints',
            name='eid',
        ),
        migrations.DeleteModel(
            name='TotalPoints',
        ),
    ]
